#These settings are used only for local dev
# Use with the DB set up in localdev.yml (See README.md)
logging:
  level:
    # Hides HHH000424: Disabling contextual LOB creation as createClob() method threw error
    org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: WARN

spring:
  datasource:
    platform: postgres
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      properties:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:/db/changelog/master.yml
